### ISSUE TITLE
Rolling a custom die with a zero on any face causes a type error

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#80]
The following rolls all produce a type error using the new 1d[x, y, z] syntax propose in #64 
```bash
!r 1d[0]
!r 1d[0, 0]
!r 1d[1, 0]
```
Rolling zero can come up in a number of situations, for example dice which span both negative and positive numbers, or a die taking attribute values, which may include zero values.

**Comment by tlackemann** [comment]
This should be fixed alongside #81

**Comment by Aquaricat** [comment]
![image](https://user-images.githubusercontent.com/7004392/34839357-f71cb184-f6c6-11e7-94bb-31aa02c23f3e.png)
Result of `!r 1d[-1, 0, 1]`

**Comment by tlackemann** [comment]
What a bug ... deploying a fix now

**Comment by Aquaricat** [comment]
Still getting 
![image](https://user-images.githubusercontent.com/7004392/34840544-ea1fae42-f6ca-11e7-848d-c2ad500b8e66.png)

**Comment by Aquaricat** [comment]
This was resolved!  Closing.
